[profile.default]
src = "src"
out = "out"
libs = ["lib"]
[profile.solc]
version = "0.8.20" 
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC}"
[etherscan]
sepolia = { key = "${ETH_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }

